### ISSUE TITLE
Can't add interfaces to systems

### ISSUE THREAD

**Issue by holmesb** [cobbler/terraform-provider-cobbler#11]
...using Cobbler v3.3.0 until Cobbler issue [#2846](https://github.com/cobbler/cobbler/issues/2846) is resolved.  Then will need to reinstate interface testing in this provider, which has been temporarily removed

**Comment by holmesb** [comment]
In testing using the feature branch that will fix #2846, realised will need to specify a default `interface_type` now otherwise terraform apply errors:
```
"Error: Cobbler System: Error adding Interface eth0 to server01: Fault(1): <class 'ValueError'>:intf_type choices include: ['NetworkInterfaceType.NA', 'NetworkInterfaceType.BOND', 'NetworkInterfaceType.BOND_SLAVE', 'NetworkInterfaceType.BRIDGE', 'NetworkInterfaceType.BRIDGE_SLAVE', 'NetworkInterfaceType.BONDED_BRIDGE_SLAVE', 'NetworkInterfaceType.BMC', 'NetworkInterfaceType.INFINIBAND']"
```

**Comment by SchoolGuy** [comment]
@holmesb I will do so today. Thanks for reminding me. Is this issue open because we don't have a release or why was this reopend?

**Comment by holmesb** [comment]
Thanks.  No, it can be closed I suppose
