### ISSUE TITLE
Upgrade to Terraform Plugin SDK v2

### ISSUE THREAD

**Issue by holmesb** [cobbler/terraform-provider-cobbler#13]
https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide

**Comment by SchoolGuy** [comment]
@hbokh Could you help out here maybe? I don't have the bandwith atm sadly.

**Comment by hbokh** [comment]
I'm sorry but I am unable to handle this for various reasons.
- at `$COMPANY` we are moving away from Cobbler and are still on v3.1.2. I am unable to test this (quickly) against the latest Cobbler version v3.3.2. Would need to setup a test env in my spare time.
- I am not a (Go) developer.  An experienced developer is definitely needed to solve this issue.
   Nevertheless I gave it a quick try / look anyway by scanning the [Terraform Plugin SDK v2 Upgrade Guide](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide).
  This is where I get stuck:


```console
$GOPATH/bin/tf-sdk-migrator v2upgrade
Rewriting provider go.mod file...
Rewriting SDK package imports...
Running `go mod tidy`...
Error running go mod tidy: exit status 1
go: finding module for package github.com/hashicorp/terraform-plugin-sdk/v2/helper/hashcode
go: finding module for package github.com/hashicorp/terraform-plugin-sdk/v2/helper/pathorcontents
github.com/cobbler/terraform-provider-cobbler/cobbler imports
	github.com/hashicorp/terraform-plugin-sdk/v2/helper/hashcode: module github.com/hashicorp/terraform-plugin-sdk/v2@latest found (v2.17.0), but does not contain package github.com/hashicorp/terraform-plugin-sdk/v2/helper/hashcode
github.com/cobbler/terraform-provider-cobbler/cobbler imports
	github.com/hashicorp/terraform-plugin-sdk/v2/helper/pathorcontents: module github.com/hashicorp/terraform-plugin-sdk/v2@latest found (v2.17.0), but does not contain package github.com/hashicorp/terraform-plugin-sdk/v2/helper/pathorcontents
```

From the changelog:

**BREAKING CHANGES**

Removed the helper/mutexkv, helper/pathorcontents, httpclient, and helper/hashcode packages. These packages can be easily replicated in plugin code if necessary or the v1 versions can be used side-by-side (https://github.com/hashicorp/terraform-plugin-sdk/issues/438)


As stated, I think someone with proper Golang knowledge can fix this easily, but sadly that won't be me...

**Comment by SchoolGuy** [comment]
Okay thanks a lot for the quick look though! @hbokh 

I guess then this will be added to the endless list of things I need to fix on the weekend.

**Comment by ByteOtter** [comment]
So I see both these modules have been removed from the `terraform-plugin-sdk` with the following notes:

Regarding the `hashcode` module: 
`Please use crc32.ChecksumIEEE directly if you need to calculate a hash for a string`

Regarding the `pathorcontent` module:
`Please copy the implementation to your own provider if you still need this code`
