### ISSUE TITLE
Release on Terraform Registry

### ISSUE THREAD

**Issue by SchoolGuy** [cobbler/terraform-provider-cobbler#2]
Sadly because you can't unfork a repo, I had to delete the old one.

Old people in this issue:

- @hbokh 
- @hansadema
- Third one who participated I forgot sadly

The URL for the provider is: https://registry.terraform.io/providers/cobbler/cobbler

I don't know but it hasn't picked up v2.0.2 yet but lets see. When it is picked up I will close this one then.

**Comment by hbokh** [comment]
Third one is @holmesb

Thanks for your work! Sadly the provider does not seem to be available at all (yet) under cobbler, though the registry says:

ALREADY PUBLISHED

cobbler/terraform-provider-cobbler

But I don't think it would take over 2 hours. Weird...

**Comment by SchoolGuy** [comment]
@hbokh If it doesn't work I will write a mail to their support.

**Comment by SchoolGuy** [comment]
Provider published and available. Thus closing this one!
