### ISSUE TITLE
Cobbler v3.3.0 compatibility

### ISSUE THREAD

**Issue by holmesb** [cobbler/terraform-provider-cobbler#9]
Eg when trying to create a profile:

```
resource "cobbler_profile" "main" { 
  name = "my_profile" 
  distro = "ubuntu2004-x86_64" 
}
```

produces error:
`[ERROR] vertex "cobbler_profile.main" error: Cobbler Profile: Error Creating: Error updating next_server to .`

next_server no longer exists in v3.3.0, are probably other schema changes besides.

**Comment by hbokh** [comment]
FYI: We're still on Cobbler 3.1.2 plus Cobbler Terraform Provider v2.0.3. No issues so far with these two.
Since we're slowly moving away from Cobbler, I don't think I / we can address the above issue anytime soon.

**Comment by holmesb** [comment]
This is becaue next_server is now next_server_v4 and next_server_v6 in v3.3.0.  I'll broaden the title of this issue as there are probably other schema changes
